name: DupePlus
main: net.meme20200.Bukkit.BukkitDupePlus
version: 1.4.2
description: The plugin that turns your server into a Dupe Server.
author: meme20200
api-version: "1.21.2"
softdepend:
  - ItemsAdder
  - PlaceholderAPI
authors:
  - GalaxyDevel0per
permissions:
  dupeplus.admin.*:
    description: All admin permissions
    default: op
    children:
      dupeplus.admin.reload: true
      dupeplus.admin.blocklist: true
      dupeplus.admin.block: true
      dupeplus.admin: true
  dupeplus.updates.notify:
    description: Notifies the player of the latest update
    default: op
  dupeplus.admin.reload:
    description: Allows the player to reload the configuration.
    default: op
  dupeplus.admin.blocklist:
    description: Allows the player to open the blocklist menu
    default: op
  dupeplus.admin.block:
    description: Allows the player to make the item undupeable
    default: op
  dupeplus.times:
    description: Allows the player to use the times
    default: true
  dupeplus.times.max.unlimited:
    description: The player will have no limit when using /dupe [times]
    default: false
  dupeplus.dupe:
    description: The player will be allowed to use /dupe
    default: true
  dupeplus.cooldown:
    description: The player will need to wait a certain amount of seconds until the player can dupe.
    default: true
